import fs from "node:fs/promises";
import path from "node:path";

type RadarItem = {
  id: string;
  title: string;
  url: string;
  source: string;
  summary: string;
  publishedAt?: string;
  score: number;
  scoreBreakdown: Record<string, number>;
  tags: string[];
  angles: string[];
  recommendation: string;
};

type RadarData = {
  generatedAt: string;
  sourceCount: number;
  itemCount: number;
  topItems: RadarItem[];
  byAction: Record<string, RadarItem[]>;
  sourceStats: Record<string, number>;
};

async function loadData(): Promise<RadarData> {
  const file = path.join(process.cwd(), "public", "data", "latest.json");
  try {
    return JSON.parse(await fs.readFile(file, "utf8"));
  } catch {
    return {
      generatedAt: new Date().toISOString(),
      sourceCount: 0,
      itemCount: 0,
      topItems: [],
      byAction: {},
      sourceStats: {},
    };
  }
}

function fmtTime(iso: string) {
  return new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Shanghai" }).format(new Date(iso));
}

function Score({ value }: { value: number }) {
  return <div className="score">{Math.round(value)}</div>;
}

function ItemCard({ item, lead = false }: { item: RadarItem; lead?: boolean }) {
  const body = (
    <>
      <div>
        <a href={item.url} target="_blank" rel="noreferrer"><h3>{item.title}</h3></a>
        <p>{item.summary}</p>
        <div className="tags">{item.tags.slice(0, 8).map((t) => <span className="tag" key={t}>{t}</span>)}</div>
        <div className="source">{item.source}{item.publishedAt ? ` · ${fmtTime(item.publishedAt)}` : ""}</div>
      </div>
      <div className="actions">
        <span className="action">{item.recommendation}</span>
        {item.angles.slice(0, 2).map((a) => <span className="pill" key={a}>{a}</span>)}
      </div>
    </>
  );
  if (lead) return <div className="lead"><Score value={item.score}/><div>{body}</div></div>;
  return <div className="item"><Score value={item.score}/>{body}</div>;
}

export default async function Home() {
  const data = await loadData();
  const lead = data.topItems[0];
  const rest = data.topItems.slice(1, 18);
  const actionRows = Object.entries(data.byAction).sort((a,b)=>b[1].length-a[1].length);
  const sourceRows = Object.entries(data.sourceStats).sort((a,b)=>b[1]-a[1]);
  return (
    <main className="container">
      <section className="hero">
        <div className="hero-main card">
          <div className="kicker">Overseas SaaS Topic Radar</div>
          <h1>海外 SaaS / AI 产品选题雷达</h1>
          <p className="subtitle">每 3 小时扫描 AIHOT、Buzzing、HN、GitHub、Dev.to、Product Hunt 等公开信号，精选适合公众号、小红书、小程序和海外 SaaS 的候选选题，并给出评分、内容角度和行动建议。</p>
          <div className="meta">
            <span className="pill">最近更新：{fmtTime(data.generatedAt)}</span>
            <span className="pill">候选信号：{data.itemCount}</span>
            <span className="pill">信息源：{data.sourceCount}</span>
            <span className="pill">更新频率：3 小时</span>
          </div>
        </div>
        <div className="hero-side card">
          <div className="metric"><strong>{data.topItems.length}</strong><span>精选候选选题</span></div>
          <div className="metric"><strong>{lead ? Math.round(lead.score) : 0}</strong><span>当前最高分</span></div>
          <div className="metric"><strong>{actionRows[0]?.[0] ?? "-"}</strong><span>主推荐动作</span></div>
        </div>
      </section>

      <section className="grid">
        <div className="section card">
          <h2>今日首推</h2>
          {lead ? <ItemCard item={lead} lead/> : <div className="empty">还没有采集到数据，先运行 npm run refresh。</div>}
        </div>
        <div className="section card">
          <h2>精选选题池</h2>
          {rest.map((item) => <ItemCard key={item.id} item={item}/>)}
        </div>
        <div className="section card two">
          <h2>推荐动作分布</h2>
          <table className="table"><tbody>{actionRows.map(([k, v]) => <tr key={k}><th>{k}</th><td>{v.length} 个</td><td>{v.slice(0,3).map(i=>i.title).join(" / ")}</td></tr>)}</tbody></table>
        </div>
        <div className="section card two">
          <h2>信息源贡献</h2>
          <table className="table"><tbody>{sourceRows.map(([k, v]) => <tr key={k}><th>{k}</th><td>{v}</td></tr>)}</tbody></table>
        </div>
      </section>
      <div className="footer">Generated by Hermes · 数据来自公开网页/API，仅作选题雷达与人工筛选参考。</div>
    </main>
  );
}
